/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayHelper */

#ifndef _Included_ArrayHelper
#define _Included_ArrayHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayHelper
 * Method:    sumOf
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_ArrayHelper_sumOf
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     ArrayHelper
 * Method:    squareAll
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_ArrayHelper_squareAll
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
