/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LegacyBox */

#ifndef _Included_LegacyBox
#define _Included_LegacyBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LegacyBox
 * Method:    getInnerVolume
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_LegacyBox_getInnerVolume
  (JNIEnv *, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
